### ISSUE TITLE
Can't open Collaborators page.

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#1134]
Nothing happens when I'm trying to click on the space Collaborators page. 
I see the following error message in console:
`NavigationError(id: 13, url: '/alkazako/mywork/settings/collaborators', error: TypeError: Cannot read property 'unsubscribe' of undefined)`

**Comment by joshuawilson** [comment]
@dlabrecq this might be related to #1128

**Comment by alexeykazakov** [comment]
It's probably the same issue but if I just open https://openshift.io/alkazako/mywork/settings/collaborators in my browser (instead of trying to click on Collaborators tab to navigate to that page) and try to add some collaborators the list of users there is always empty. I don't see any requests to backend to search users by name.

**Comment by dlabrecq** [comment]
Fixed by https://github.com/fabric8-ui/fabric8-ui/pull/2116

**Comment by alexeykazakov** [comment]
@dlabrecq the navigation works now but I still can't add collaborators. There is no any requests to backend to search users. See my previous comment. Should we create a new issue for that?

**Comment by joshuawilson** [comment]
I think we can use this one, it is the same issue.

**Comment by dlabrecq** [comment]
I think that may be an issue with not retrieving the right tokens? I suspect ths may begin working after https://github.com/openshiftio/openshift.io/issues/955#issuecomment-337140183 is fixed?

**Comment by alexeykazakov** [comment]
No tokens required (from the backend side) to search for users. And I don't see any requests to backend at all.

**Comment by dlabrecq** [comment]
I have a lot of websocket errors in my page, failed with HTTP authorization. I suspect there are no collaborators to add because a list cannot be retrieved?

Once we have the UI in a more stable state, I can better debug this.

**Comment by alexeykazakov** [comment]
@mishaone has created a separate issue for the user list issue -  https://github.com/openshiftio/openshift.io/issues/1140
I'm closing this one because the original issue in the description was about the navigation part. Navigation now works so let's track the user list bug in https://github.com/openshiftio/openshift.io/issues/1140
