### ISSUE TITLE
[codebases]Arrow of the hover of the + sign is shifted

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1179]
![image](https://user-images.githubusercontent.com/1105127/31815982-bc6b70e4-b58e-11e7-82f8-ee55b1c8acda.png)

**Comment by joshuawilson** [comment]
@mindreeper2420 can you look at this, when you have time.

**Comment by joshuawilson** [comment]
@mindreeper2420 this appears releated to #1181

**Comment by mindreeper2420** [comment]
@joshuawilson @apupier I believe that this is fixed by the fix for #1181. Can I get a second verification?

**Comment by mindreeper2420** [comment]
should be fixed with PR https://github.com/fabric8-ui/fabric8-ui/pull/2215

**Comment by joshuawilson** [comment]
@mindreeper2420 this is not fixed. If you reduce the screen height so that it will need a scroll bar then the "plus" moves as the scroll bar tries to appear.

**Comment by mindreeper2420** [comment]
@dlabrecq can you assist? The more I look at it, the more it feels like the bootstrap-tooltip module is having issues.

**Comment by dlabrecq** [comment]
That's just the nature of the ngx-bootstrap tooltip. It's going to shift over because there isn't enough room. However, it would probably look a lot better if you simply make the tooltip appear on the left.

FYI, the PatternFly tooltip uses some CSS trickery to better align the arrow. It's possible we could do the same for ngx-bootstrap, but it would take some effort.

**Comment by dlabrecq** [comment]
FYI, the new spaces page design shows "Create Space" text, to the right of the plus icon, which launches the space wizard. For consistency, perhaps we want to add "Add Codebase" to the right of the plus icon for the codebases page? That would definitely give the tooltip enough room for the arrow to align properly.

![screen shot 2017-11-19 at 10 20 47 pm](https://user-images.githubusercontent.com/17481322/33000757-ff9d38ce-cd77-11e7-9dd7-7d5bbce6edb6.png)
