### ISSUE TITLE
Update of Learn more page

### ISSUE THREAD

**Issue by pkettman** [openshiftio/openshift.io#2050]
The Learn more page is not well formatted in my Chromium browser v56.0.2924.87 (see the picture below), there is no white space on the left/right side and text & pictures are in one column. I sometimes can't access the Learn more page from my 6 months old Chrome, in that case I am moved back to the homepage. On Firefox it works fine.

In addition I would propose to link the User & Getting Started Guides (currently in the drop down menu) also from the Learn more page, as it is accessible & visible directly from the Account homepage where users start learning & experimenting. I believe the sooner users get to these guides the less misunderstandings, confusion they can get into.

![obrazek](https://user-images.githubusercontent.com/26871874/35381594-1b374c68-01bd-11e8-8c16-f6947edb1363.png)

**Comment by qodfathr** [comment]
@joshuawilson @aslakknutsen does this potentially look like a variation of #1975?

@ldimaggi note reported issue with Chromium v56.0.2924.87. As we continue to define #2018, hopefully we'll be in a position to say more about our expectations for that browser version to work.

**Comment by joshuawilson** [comment]
No this is about the docs not the main application.

**Comment by qodfathr** [comment]
@joshuawilson do you know who owns features.html?

**Comment by joshuawilson** [comment]
@qodfathr yes, that is UXD. I think @mindreeper2420 does the work on it.

**Comment by mindreeper2420** [comment]
Per the [Wiki](https://github.com/openshiftio/openshift.io/wiki/Supported-Browsers), OpenShift.io requires Chrome v60.x or higher. At a minimum, for the site to render correctly, [Chrome v57.x](https://developers.google.com/web/updates/2017/03/nic57) must be used, as that was the first version to support the CSS styles/techniques that are in use. Chrome v57.x was released March 2017 for MacOS, Windows and Linux.

Firefox support begins at version 54, released June, 2017.

@qodfathr Do you want the changes, as suggested for linkage, made? This page is actually the Features page, not Learn More (that is a mislabel on the home dashboard). Should we be surfacing User & Getting Started Guides before they are in the system?

**Comment by qodfathr** [comment]
@mindreeper2420 I think my main concern right now is that we have a static HTML page (features.html) which does not render in a web browser produced in the last 10 years. Given that this page is a marketing page meant to convince people to try out the service, it should be made as backwards compatible as possible (IMHO).

FYI, the Wiki will soon be wrong and require updating, once we finish authoring #2018.

**Comment by mindreeper2420** [comment]
@qodfathr Ok, I will add this to the UX issue list for this sprint. I will also update the Getting Started page, as that uses the same CSS techniques as the Features page.

**Comment by mindreeper2420** [comment]
This should be fixed with the latest update. I’ve verified in emulators, but can someone else verify as well?

**Comment by pkettman** [comment]
The Learn more page layout is formatted fine now. But I still can't get to the page from the OSIO homepage on my Google Chrome V61.0.3163.100.

**Comment by joshuawilson** [comment]
@pkettman there is a link in the center of the page below the image of the laptop that is called `Learn more about the features`. There is also the `Features` link in the header. Do these not work for you?

**Comment by pkettman** [comment]
When I click the "Learn more" link on the homepage, whole text is: "Learn more what Openshift.io can do for you." I can't get to the Learn more page and I am moved back to the homepage, see below. This happens only in my Chrome V61.0.3163.100 and works fine with Firefox and Chromium v56.
![osio_homepage](https://user-images.githubusercontent.com/26871874/36101800-a931ff9e-100a-11e8-8bb9-f8d4467cd0b8.png)

**Comment by joshuawilson** [comment]
Ah, I thought you were talking about the main landing page. Once you are logged in if you click that link it opens up the Learn more page in a new tab.

**Comment by pkettman** [comment]
Yes, a new tab is opened with url https://openshift.io/_gettingstarted but after some seconds it's from an unknown reason forwarded to https://openshift.io/_home.

**Comment by joshuawilson** [comment]
@catrobson can you please look into this with regard to how we link to docs?

**Comment by mindreeper2420** [comment]
@joshuawilson documentation linking has been updated, per https://github.com/fabric8-ui/fabric8-ux/issues/874 (all associated PRs attached to that).

Can you and @pkettman verify if this is still an issue or not? It went from browser rendering support to documentation, so I'm not quite sure if both have been fixed or not. :)

**Comment by joshuawilson** [comment]
With the updates to the links on the page it appears to work. I'm going to close this.
@pkettman if you are still having issues, please reopen this.
