### ISSUE TITLE
Unable to start workspace pod on prod-preview - Failed to pull image

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#2181]
Today, we are unable to start centos-jdk8 stack workspace pod on prod-preview.
This is relevant part of output of `oc get events` on free-stg:
```
1h         1h          3         che-ws-ew32qqhs1ka2999h-1858262212-68k4w   Pod          spec.containers{ew32qqhs1ka2999h-machineyew55412fsq6kpj9-kkanova-osiotest1-dev}   Normal    Pulling                 kubelet, ip-172-31-76-218.us-east-2.compute.internal   pulling image "docker-registry.default.svc:5000/kkanova-osiotest1-che/registry.devshift.net_che_vertx:ew32qqhs1ka2999hyew55412fsq6kp"
1h         1h          3         che-ws-ew32qqhs1ka2999h-1858262212-68k4w   Pod          spec.containers{ew32qqhs1ka2999h-machineyew55412fsq6kpj9-kkanova-osiotest1-dev}   Warning   Failed                  kubelet, ip-172-31-76-218.us-east-2.compute.internal   Failed to pull image "docker-registry.default.svc:5000/kkanova-osiotest1-che/registry.devshift.net_che_vertx:ew32qqhs1ka2999hyew55412fsq6kp": rpc error: code = 2 desc = Get https://docker-registry.default.svc:5000/v1/_ping: x509: certificate is valid for docker-registry-default.1b7d.free-stg.openshiftapps.com, docker-registry.default.svc.cluster.local, 172.30.44.192, not docker-registry.default.svc
1h         1h          3         che-ws-ew32qqhs1ka2999h-1858262212-68k4w   Pod          spec.containers{ew32qqhs1ka2999h-machineyew55412fsq6kpj9-kkanova-osiotest1-dev}   Warning   Failed                  kubelet, ip-172-31-76-218.us-east-2.compute.internal   Error: ErrImagePull
```
But when I'm starting another type of workspace, for example centos-nodejs, everything is fine:
```
1h         1h          1         che-ws-fl6zq5qc1vodkbqa-3865160548-6h7cj   Pod          spec.containers{fl6zq5qc1vodkbqa-machinee4qoubt0nktnrb1u-kkanova-osiotest1-dev}   Normal    Pulling                 kubelet, ip-172-31-76-218.us-east-2.compute.internal   pulling image "172.30.44.192:5000/kkanova-osiotest1-che/registry.devshift.net_che_vertx:fl6zq5qc1vodkbqae4qoubt0nktnrb"
1h         1h          1         che-ws-fl6zq5qc1vodkbqa-3865160548-6h7cj   Pod          spec.containers{fl6zq5qc1vodkbqa-machinee4qoubt0nktnrb1u-kkanova-osiotest1-dev}   Normal    Pulled                  kubelet, ip-172-31-76-218.us-east-2.compute.internal   Successfully pulled image "172.30.44.192:5000/kkanova-osiotest1-che/registry.devshift.net_che_vertx:fl6zq5qc1vodkbqae4qoubt0nktnrb"
```
It seems, that in one case, it pulls the image from 172.30.44.192:5000 and in the other case it tries to pull it from docker-registry.default.svc:5000. It seems like this openshift origin issue: https://github.com/openshift/origin/issues/16097

@kbsingh Could this be related to free-stg update?

## Steps to reproduce:
1) Open che.prod-preview.openshift.io
2) Create new workspace with "Java CentOS" stack.
3) Workspace is created, but it's unable to start.

**Comment by ibuziuk** [comment]
having the same problem for vertx stack:

> 
Failed to pull image "docker-registry.default.svc:5000/ibuziuk-che/registry.devshift.net_che_vertx:moozfstyck4ird1g484aykxw65zsn8": rpc error: code = 2 desc = Get https://docker-registry.default.svc:5000/v1/_ping: x509: certificate is valid for docker-registry-default.1b7d.free-stg.openshiftapps.com, docker-registry.default.svc.cluster.local, 172.30.44.192, not docker-registry.default.svc

**Comment by rhopp** [comment]
It seems, that today it's stack independent...

**Comment by pbergene** [comment]
Over the past few days free-stg has been upgraded from 3.7 to 3.9.
Earlier this week it has had differing versions on compute and master nodes (and kubernetes versions), but now it has settled on 3.9 & 1.9, so the target we are testing against has stabilized.

So as we are still experiencing it, we should be taking into consideration that this can be a result of the version change.

**Comment by pbergene** [comment]
I'll read the issue before commenting, this looks like something that has changed during the upgrade that should be fixed infra side @jfchevrette

**Comment by jfchevrette** [comment]
I've reached out to the folks running the staging. Will report here once I have more info & a fix

**Comment by jfchevrette** [comment]
Fix is being built and applied today. Will report here once that is done so we can validate.

**Comment by jfchevrette** [comment]
This should be resolved. Please validate & close

**Comment by rhopp** [comment]
Hi @jfchevrette we are still seeing this issue on prod-preview.
![image](https://user-images.githubusercontent.com/1215011/36089991-d45cb21c-0fde-11e8-977f-262827af437e.png)

**Comment by jfchevrette** [comment]
Should be fixed for real now.

**Comment by rhopp** [comment]
Yep... Working as expected. Thanks.
Closing.
