### ISSUE TITLE
Applications with maximum character length (63) can't build in Jenkins

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2527]
I created an application with maximum character length and the pipeline build is permanently stuck at, for example:
```
Jenkins doesn’t have label mavenarstarstarstarstartsarstarstarstarstarstarstarstarstarstarstars_2
```

Cancelling the build and then starting it again results in the same issue.

Steps to reproduce:

1. Use quickstart wizard to create an application (vert.x http booster). In step 1B, set OpenShift Project Name to be a 63 character length name. Continue through to the end, creating a Release and Stage Or Release, Stage, Approve, Promote Pipeline.
2. See pipeline build fail via Jenkins logs.

**Comment by joshuawilson** [comment]
Please explain exactly what you did to produce this and where you found the bug. 
Please add labels for `area`, `team`, and `severity` if you know them.

**Comment by jiekang** [comment]
@joshuawilson I've added steps to reproduce. I'm not sure on the severity, area, or team for this.

**Comment by joshuawilson** [comment]
@jiekang this looks like something for @chmouel and the build team.

**Comment by piyush1594** [comment]
I tried to reproduce this and I am also facing the issue 

Jenkins Log
```
[Pipeline] echo
Loaded PipelineConfiguration PipelineConfiguration{jobNameToKindMap={}, ciBranchPatterns=[PR-.*], cdBranchPatterns=[master], cdGitHostAndOrganisationToBranchPatterns={}, disableITestsCD=false, disableITestsCI=false, useDockerSocketFlag=false}
[Pipeline] echo
Loaded the useDockerSocket flag false
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
Jenkins doesn’t have label mavencjdncdjcjdjfjfjjfjfjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj_1
```

**Comment by pradeepto** [comment]
@piyush1594 are you working on the fix for this? If so, please assign it to yourself.

**Comment by rupalibehera** [comment]
`Jenkins doesn’t have label mavencjdncdjcjdjfjfjjfjfjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj_1` this comes from some plugin I don't think so we can fix it directly. it should be fixed in the plugin.

**Comment by lordofthejars** [comment]
Ok then if it comes from plugin, then maybe we can un UI make a quick validation that don't let user write more than 62 chars, so we are not reaching the limit. I am going to try now if this is enough, and if so, then this could be a workaround.

**Comment by lordofthejars** [comment]
Ok I tried with 62 chars and the same problem, then I tried with 32 and it worked so I think is totally stupid to start trying where is the limit, maybe the solution is just analyze how many characters can contain a project name (let's say 50 or 40) try if it works, and if it works just change the limit in the UI. I think it is a quick fix and we will not be able to spend so much time searching in the plugin list, find the plugin, find why this happens, send PR, wait for release, ....

CC/ @pradeepto @joshuawilson @krishnapaparaju

**Comment by joshuawilson** [comment]
If that is the solution we want to go with then we need the new launcher team to update the wizard.
@animuk @arunkumars08 @jyasveer

**Comment by lordofthejars** [comment]
@joshuawilson I am just trying to find a solution for the problem since fixing in plugin side might take a lot of time and probably it is out of our control.

**Comment by jiekang** [comment]
Does it need to use the application name for the label? Is there a id/hash that's less than 63 characters? Might require a lot of changes across the board to though; just a suggestion.

**Comment by lordofthejars** [comment]
But what I was thinking here is just in frontend, to not allow more than 40
chars

**Comment by jiekang** [comment]
This is a similar issue regarding naming issues:

https://github.com/openshiftio/openshift.io/issues/2370

Todd responded there that we need to be robust against third-party name restrictions. Reducing the character limit on our front-end is indeed a possible fix however I think it will need approval.

**Comment by qodfathr** [comment]
As long as #3391 is a p0, we can remove p0 from here.

**Comment by piyush1594** [comment]
@pradeepto @krishnapaparaju @sthaha @maxandersen Is there need to fix this in build.now. The fix is the pipeline is already there to limit the name to 40 chars.

**Comment by maxandersen** [comment]
since >40 on names is still going to happen it would make sense to figure out why this is failing to actually know why the limit is necessary to be there.

**Comment by hrishin** [comment]
### Problem:

The root cause of this problem is if the application name is greater than 64 characters then Jenkins not able to spinup slave pod. The application name is used as an identifier at every place, in this case, to generate a label for slave pod.

error log from Jenkins

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/api/v1/namespaces/hshinde-jenkins/pods?labelSelector=jenkins%3Dslave,jenkins/mavendummy_project_jagdgsajgdjgsajgdjsagjdgasjgdjgsajgd1994118_1%3Dtrue . Message: unable to parse requirement: invalid label key "jenkins/mavendummy_project_jagdgsajgdjgsajgdjsagjdgasjgdjgsajgd1994118_1": name part must be no more than 63 characters. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=unable to parse requirement: invalid label key "jenkins/mavendummy_project_jagdgsajgdjgsajgdjsagjdgasjgdjgsajgd1994118_1": name part must be no more than 63 characters, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
--
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
  | at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.addProvisionedSlave(KubernetesCloud.java:454)
  | at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.provision(KubernetesCloud.java:403)
  | at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:715)
  | at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:320)
  | at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:61)
  | at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:809)
  | at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
  | at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
```
### Possible Solutions: 
1) Retsrict application name to 49 characters max (from backend as well). K8's restriction is 64, 15 characters is taken by lable prefix and suffix.
2) Generate short lables in kubernetes Jenkins plugin to process slave pods. This is bit tricky because these lables logic reffered at many places, could be biit extensive to work on it.

**Comment by hrishin** [comment]
@gastaldi we have tried to apply validation on project length https://github.com/fabric8-launcher/launcher-backend/pull/468 in launcher backend. Looks like this change is in the production.

When we create a project with more than 49 characters it's accepting the launch request but expected behavior to get HTTP 400 response. 

Could you please confirm it once?

**Comment by jiekang** [comment]
Will this need any changes on the UI side? Maybe there needs to be coordination with the people working on the application wizard?

**Comment by gastaldi** [comment]
@hrishin now I realized that the PR is changing the wrong ProjectileContext implementation. Your PR changed the /launcher/launch endpoint, when it should have impacted /osio/launch

This is the correct one: https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/projectiles/context/OsioImportProjectileContext.java

Can you undo the changes in that PR and move it to that class instead? Sorry for the trouble

**Comment by hrishin** [comment]
> Will this need any changes on the UI side? 

@jiekang we have to make sure 49 max. char. limit for application name from UI as well.

@gastaldi I can try.

**Comment by hrishin** [comment]
This issue has been fixed in the backend. Now application name could exceed the given limit.

**Comment by vladyslovestepanov** [comment]
Hello @hrishin @joshuawilson @lordofthejars @animuk @arunkumars08 @jyasveer

I presume the issue still exists.
The project does not build with 77 characters name length for а full project name:(including branch name)

For a project with 77 lengths (**for instance** Namespace/my-project-which-should-build-on-name/feature-for-a-service-branch) it's does not build
I had to create a new branch with a new name with 56 (**, for instance,** Namespace/my-project-which-should-build-name/branch-name) - and it's built successfully

Steps to reproduce:
1. Push and build a project with at least 77 characters (likely with less number, but definitely more 56) for а full project name

Do I need to provide more information or create a separate issue?
Thank you in advance

**Comment by joshuawilson** [comment]
This repo is/was for a application/service run by Red Hat. The service has been shut down. How are you running the application that you are running into this issue?

**Comment by vladyslovestepanov** [comment]
sorry for lack of knowledge, I am a newbie here
But my application then supposed to be deployed on google cloud with Kubernetes
Am I answered your question?

**Comment by joshuawilson** [comment]
What is the URL for the service that you are trying to deploy your application with? 
I will try to redirect you to the right repo. This repo is deprecated, no one is working on it.

**Comment by vladyslovestepanov** [comment]
It's a private repo, I can not share the name
And it can be that multiple projects will face up with naming length issue
Is it feasible to solve this issue on a higher level to allow more than 63 characters for a Full project name?

**Comment by joshuawilson** [comment]
By posting here you are asking for a fix to the code in this repo. This repo is no longer a running service. 
If you have forked this repo then you are maintaining a fork. 
If you are running your app on OpenShift then the answer to my question is OpenShift. "openshift.io" does not exit any more so questions here would not fix your issue.

**Comment by vladyslovestepanov** [comment]
Okay, thank you
I will create a new issue if I face up with it again

**Comment by joshuawilson** [comment]
I'm trying to find the right place to send you so you can get your issue addressed. 
Posting here though will not help as this repo is shutdown and no longer under development.

**Comment by vladyslovestepanov** [comment]
okay, thank you
Just did not want to duplicate issue

**Comment by joshuawilson** [comment]
Are you deploying your app to OpenShift?
Or is this a Jenkins issue?

**Comment by vladyslovestepanov** [comment]
it's Jenkins issue
sorry for misleading

**Comment by joshuawilson** [comment]
Then I suggest going to the [Jenkins](https://github.com/jenkinsci/jenkins) repo and posting your question there. 

I wish the best in your coding.

**Comment by vladyslovestepanov** [comment]
thank you a lot!
