### ISSUE TITLE
fix dual access to 'dual' openshift so launch works with openshift.io  

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#292]

**Comment by joshuawilson** [comment]
@maxandersen please add a description. I'm unsure what this means.

**Comment by maxandersen** [comment]
updated - hope it makes it more clear. @alexeykazakov should be aware on the auth side of this.

**Comment by alexeykazakov** [comment]
Short term solution would be some better UX on OSO side to re-provision users in openshift.io cluster when requested. There is ongoing discussion with the OSO team about this.
Long term solution would be proper multi cluster support when openshift.io can work with users provisioned to different clusters.

**Comment by qodfathr** [comment]
Anyone one to comment on the state of this (including @ALRubinger )? Has this been addressed yet or is it still an open issue?

**Comment by alexeykazakov** [comment]
We (OSIO Auth) would need some input from the launcher team. It’s not clear to me what launcher needs from OSIO in terms of Auth.

**Comment by ALRubinger** [comment]
Per Jake Lucky on the OSO team, requesting provisioning on OSIO (us-east-2: Ohio) is no longer considered a "Starter" cluster, and will not prevent provisioning on other Starter clusters.

**Comment by maxandersen** [comment]
@ALRubinger does that mean no matter if you start at launcher site or openshift.io you don't get excluded from the other ?

**Comment by ALRubinger** [comment]
@maxandersen For new provisioning requests, that is my understanding.  ie: If I am awaiting OSIO access and request Starter, I may be given an instance on Starter us-east-1 or other.

**Comment by qodfathr** [comment]
@ALRubinger @maxandersen so, this is fixed? I definitely see that people awaiting OSIO have been able to get OSO on another cluster.

**Comment by maxandersen** [comment]
Just to keep updated - I have a feeling this is not solved as even if 
launcher can handle multiple OSO's then what happens if you signup for 
OSO before openshift.io - openshift.io
don't (yet) manage all starter clusters.

Long story short - I want to actually test this (but can't right now as 
I'm on a plane :)

/max
http://about.me/maxandersen
