### ISSUE TITLE
Update feature flags indicator color/icon

### ISSUE THREAD

**Issue by mceledonia** [openshiftio/openshift.io#3332]
Updating the current feature flags indicator to use only 1 icon (flask) with different colors that represent different levels of feature. Also introduce transparency hover state as a temporary solution to reduce content blockage. 

This is a compromise solution to make the design better for summit. After summit we will explore other shapes/locations for the feature flag indicator that isn't a "floating action button" pattern.

https://redhat.invisionapp.com/share/4EEE2JAQ7

This solution reduces confusion and misinterpretation of the other icon/color combos by using only 1 icon. It provides a temporary solution to content blocking with the transparency hover state, however this problem will be fully resolved with a post-summit iteration when there is more time for implementation.

@corinnekrych @xcoulon @catrobson

**Comment by christianvogt** [comment]
Can we also move the indicator further into the corner than it currently is. It seems oddly placed further in from the right than from the bottom. Perhaps this was done to accommodate the size of the tooltip but then we should instead fix the tooltip placement.

Furthermore do we need to show the indicator even when there are no features present? This seems to only be the case for opt-in !== production only.

![image](https://user-images.githubusercontent.com/14068621/39328253-caf7c93c-4968-11e8-8197-4efe56f9081e.png)

**Comment by mceledonia** [comment]
@christianvogt @corinnekrych The indicator should not be shown if there are no features present. 

[See this slide of the design doc](https://redhat.invisionapp.com/share/4EEE2JAQ7#/293847673_Feature_Indicator_Presummit_10)

**Comment by joshuawilson** [comment]
I think this is fixed, can you confirm

**Comment by mceledonia** [comment]
I am still seeing the old placement, here's a screenshot.
![image](https://user-images.githubusercontent.com/30935938/39472805-910ca3be-4d19-11e8-934a-e105b13bfc16.png)


Also another quick change, please make the backgrounds of both the selected button and tooltip panel white #ffffff as seen here:

![image](https://user-images.githubusercontent.com/30935938/39472814-9d60f642-4d19-11e8-8586-8b0a3077aa57.png)
