### ISSUE TITLE
Jenkins servers un-idled in loop across all clusters

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#4306]
'Something' is causing the Jenkins servers to come alive roughly every 10-20min. Seems to effect cluster 1a the hardest by starting ~250 servers, but all clusters show the same behavior. 

![screenshot from 2018-09-10 13-55-17](https://user-images.githubusercontent.com/132158/45296106-44e12280-b501-11e8-82c0-7841f6014a38.png)

**Comment by aslakknutsen** [comment]
Findings:

Jenkins-Idler service is restarting on a 20min ish interval as it's crash looping due to out of memory.

    kubernetes.labels.deploymentconfig: "jenkins-idler" AND message:"Log for pmcd on"

Jenkins-Idler service seems to be having issues with an EOF reading from the Build Watch API of OS (33 million times the past 24h):

    kubernetes.labels.deploymentconfig: "jenkins-idler" AND msg:"EOF"

Jenkins-Idler service seems to be attempting to un-idle jenkins over and over (50k times the past 24h) 

    kubernetes.labels.deploymentconfig: "jenkins-idler" AND msg:"Successfully un-idled service jenkins"

**Comment by pbergene** [comment]
@chmouel Are those lastUpdate times coming from the dc?  If so I'll check the state of some of those users lastupdate on the cluster. 

cc @jfchevrette @mmclanerh

**Comment by pbergene** [comment]
@chmouel also, if you don't mind, could we remove the user references from the public issue please? :)

**Comment by chmouel** [comment]
@pbergene yes they are coming from the DC,

**Comment by jfchevrette** [comment]
A lot of users jenkins DCs were scaled down to 0 last week on Friday to lower the load on the Gluster clusters which were under stress following a tenant update. Possibly related?

**Comment by mmclanerh** [comment]
This was happening prior to the scale down.

**Comment by chmouel** [comment]
Fixed the EOF error with https://github.com/fabric8-services/fabric8-jenkins-idler/commit/33d06182dfc6ea408df16ef35703776b2c5251ee and deployed to prod, we still have works on the unidling issue,

**Comment by pbergene** [comment]
Thanks for the update!

**Comment by aslakknutsen** [comment]
No longer effecting prod, but root cause still not fixed. Downgrading to Sev-2

https://chat.openshift.io/developers/pl/tn6egyhtntdapxkwbu6dcrcmeo

**Comment by sthaha** [comment]
I am going to add more logs to idler to understand why `user-idler` part idles/ unidles pods as a part of solving  https://github.com/openshiftio/openshift.io/issues/4215. Once we have the logs we should have better insights into the "decision" making process of idler which at the moment is hard to figure out without logs.

**Comment by chmouel** [comment]
I think we have quite a bit of logs but I guess if you think that helps,

What about some Prometheus checks? send idling/unidling/deployment
etc. ? Maybe we can have some correlations with ELK ?

**Comment by sthaha** [comment]
Closing this issue in favour of https://github.com/openshiftio/openshift.io/issues/4340 since the idle/unidle loop doesnt happen anymore.
