### ISSUE TITLE
Internal Server Error when trying to create application (launcher)

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#4539]
##### Issue Overview

App creation fails after resetting environment because of incorrect space ID.

##### Expected Behaviour
Creating a new application should use correct `space_id` and should not fail with `500: Internal Server Error`

##### Current Behaviour
New app creation fails with Internal Server Error after resetting environment. The `space_id` used to create the new application is the incorrect one.

##### Steps To Reproduce

1. Create space, application, pipelines
2. Reset environment
3. Create a new space and try to create an application. It fails with `500: Internal Server Error`

##### Additional Information

The following request was sent from the browser
```
curl 'https://forge.api.prod-preview.openshift.io/api/osio/launch' \
    -H 'Origin: https://prod-preview.openshift.io' 
    -H 'Accept-Encoding: gzip, deflate, br' \
    -H 'X-Git-Provider: GitHub' \
    -H 'X-App: osio' \
    -H 'Authorization: Bearer xxx' \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    -H 'Accept-Language: en-US,en;q=0.9' \
    -H 'Accept: application/json, text/plain, */*' \
    -H 'Referer: https://prod-preview.openshift.io/ijarif-preview/testspace/applauncher/createapp/dgdfg' \
    -H 'X-Execution-Step-Index: 0'  \
    --data 'projectName=dgdfg&projectVersion=1.0.0&groupId=io.openshift.booster&artifactId=booster-mission-runtime&space=/c744c52a-31c7-498b-bb33-dce6182bce84&targetEnvironment=os&gitRepository=dgdfg&pipeline=maven-releaseandstage&mission=health-check&runtime=spring-boot&runtimeVersion=current-redhat' \
   --compressed
```
and the follwoing was the response
```
[{message: "Context space not found: /c744c52a-31c7-498b-bb33-dce6182bce84"}]
0: {message: "Context space not found: /c744c52a-31c7-498b-bb33-dce6182bce84"}
```

I can confirm I do not have any space with id `c744c52a-31c7-498b-bb33-dce6182bce84`

**Comment by joshuawilson** [comment]
Did you use the same name for the space?
I'm wondering if it might be some caching issue.

@alexeykazakov I'm adding Platform since it has to do with Resetting the Env and Space IDs.

**Comment by alexeykazakov** [comment]
I have no idea how reset env in backend can cause such issue. Looks like an UI issue to me. The wizard uses some wrong space ID.

**Comment by alexeykazakov** [comment]
@sbose78 @rohitkrai03 maybe you can take a look guys.

**Comment by joshuawilson** [comment]
The reset is done in the backend, something on the tenant services. The Space ID is set by the backend. I don't know how the UI could cache the ID but it might.

**Comment by vikram-raj** [comment]
I follow the steps as mentioned by @jarifibrahim but not able to reproduce this issue.

I tried on prod and on prod-preview as well.

**Comment by piyush-garg** [comment]
@vikram-raj @jarifibrahim @joshuawilson I also faced this issue, reloading the page works for me.

**Comment by jarifibrahim** [comment]
> I follow the steps as mentioned by @jarifibrahim but not able to reproduce this issue.
> 
> I tried on prod and on prod-preview as well.

I was playing around with che and build so I had created and deleted a lot of spaces and builds. I think I cleaned the environment a couple of times.

**Comment by bartoszmajsak** [comment]
If the reloading the page fixes the behaviour it might mean we are caching / storing this value globally. @vikram-raj did you have a chance to analyze the code which is responsible for this interaction?

**Comment by jarifibrahim** [comment]
I can no longer reproduce this issue. Maybe it was fixed because I did a `reset environment`.
I'm closing this since it cannot be reproduced.

**Comment by ldimaggi** [comment]
Same issue as #4546 - which also seems to be fixed now.

**Comment by piyush-garg** [comment]
I am still facing the issue

Steps to reproduce:-

1. Create a space - test
2. Create an application
3. Reset Environment
4. Create space again with the same name
5. Create an application and it will throw the same error at the time of clicking `setup application`

If you refresh at this stage, it will work.

Thanks

**Comment by jarifibrahim** [comment]
I encountered this issue again.
What did I do?
 - Reset my environment
 - Create a new space and try to import a codebase

**Comment by joshuawilson** [comment]
I don't think this is a UI issue. It appears to be a conflict with the Space ID and it not being cleaned properly  during the reset.
@sbose78 @alexeykazakov what part of the backend deals with this? Please add the correct team.

**Comment by jarifibrahim** [comment]
@joshuawilson Look at this peice of [code](https://github.com/fabric8-launcher/ngx-launcher/blob/be52635774b3b10ea899c3a6bb3150936d3387fe/projects/ngx-launcher/src/lib/components/targetenvironment-step/target-environment-review.component.html#L67-L72)
```
          <div class="form-group f8launcher-project-summary-data-form-group" *ngIf="data.spacePath">
            <label class="col-xs-4 control-label">Space Path</label>
            <div class="col-xs-8 f8launcher-project-summary-data-field">
              <span>{{data.spacePath}}</span>
            </div>
          </div>
```

The spacePath comes from a shared variable. 
```
  ngOnInit(): void {
    this.data = this.projectile.getState(this.stepId).state;
  }
```
See https://github.com/fabric8-launcher/ngx-launcher/blob/bb237b009f01980064642267acda1ba377af9e5a/projects/ngx-launcher/src/lib/review.component.ts#L12-L14

This shared state contains the old value of spaceID. This is a UI or a Launcher Issue (whoever sends that spaceID).

**Comment by edewit** [comment]
@joshuawilson seems to be a front-end issue, there is a service that get the space and other custom settings and it's used to add to the users settings, so it should always set spaceId instead using `_.defaults`

https://github.com/fabric8-launcher/ngx-launcher/blob/master/projects/ngx-launcher/src/lib/components/project-summary-step/project-summary-step.component.ts#L44-L48

**Comment by edewit** [comment]
@joshuawilson seems the `context` that includes the `spacePath` is cached here: https://github.com/fabric8-ui/fabric8-ui/blob/60d966dbd24071454e7cc0a64d17224b10520d3a/src/app/space/app-launcher/services/app-launcher-dependency-check.service.ts#L12

**Comment by joshuawilson** [comment]
Oh, that makes sense. Thanks @edewit
