### ISSUE TITLE
Errors (non-fatal, non-blocking) displayed when opening a Che workspace

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#531]
These errors are logged to the dev-machine console when a Che workspace is opened:

```
[STDERR] chown: changing ownership of ‘/projects’: Operation not permitted
.
.
.
[STDERR] chown: changing ownership of ‘/projects’: Operation not permitted
[STDERR] chmod: changing permissions of ‘/projects’: Operation not permitted
```

There does not seem to be any functional impact from these errors, but they may confuse/alarm users.

**Comment by rgarg1** [comment]
@ldimaggi I've seen that too.

**Comment by l0rd** [comment]
I've created https://github.com/redhat-developer/rh-che/issues/298 to plan to investigate that for next sprint

**Comment by l0rd** [comment]
A PR that should fix that has been opened upstream https://github.com/eclipse/che/pull/6416

**Comment by slemeur** [comment]
@l0rd : I'm still seeing the on 2.0.35

![screen shot 2017-10-12 at 19 54 29](https://user-images.githubusercontent.com/1636769/31511211-4776ed70-af87-11e7-8181-7cd755504240.png)

**Comment by l0rd** [comment]
@slemeur we need to set Che upstream version to `5.19.0` to get this fix to osio. That's planned for next week.

**Comment by slemeur** [comment]
Ok thanks @l0rd !

**Comment by ibuziuk** [comment]
@l0rd this should be fixed right ?

**Comment by l0rd** [comment]
@ibuziuk I am afraid we need to wait for Che `5.21.0` to reach OSIO. This PR should fix the last STDERR message https://github.com/eclipse/che/pull/7471

**Comment by ibuziuk** [comment]
verified on prod. Closing
