### ISSUE TITLE
If a user imports more than one github repo ("import existing code") - the import is successful - but the success dialog includes subsets of each repo's information

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#532]
To recreate:
* In a clean OSIO user account, import more than one github repo

See the attached screenshot for the success dialog:

![screenshot from 2017-08-09 15-00-04](https://user-images.githubusercontent.com/642621/29139442-f58caef4-7d14-11e7-9c64-3ae5e4b06560.png)

**Comment by ldimaggi** [comment]
For this test, the vertex paint and event bus repos were imported at the same time. The UI allows users to select multiple repos to import.

**Comment by joshuawilson** [comment]
related to https://github.com/fabric8-ui/fabric8-ui/issues/1857
fixed in https://github.com/fabric8-ui/fabric8-ui/pull/1858
@ldimaggi please validate

**Comment by ldimaggi** [comment]
This is still a problem - see:

![screenshot from 2017-08-13 22-06-16](https://user-images.githubusercontent.com/642621/29255927-ea880a00-8073-11e7-9b90-85fa59b5ea63.png)

**Comment by corinnekrych** [comment]
fixed in https://github.com/openshiftio/openshift.io/issues/966
