### ISSUE TITLE
If Che pod is down, and user attempts to create codespace, no error is reported to user

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#667]
Related to: https://github.com/openshiftio/openshift.io/issues/618

If Che is down, the user's attempt to create a Che codepsace will fail, but no error will be reported to the user through the OSIO UI. The chrome console log reports:

```
POST https://api.openshift.io/api/codebases/2bf7cac5-043a-4d40-988e-8a1d26ea6768/create 504 (Gateway Time-out)
create:1 XMLHttpRequest cannot load https://api.openshift.io/api/codebases/2bf7cac5-043a-4d40-988e-8a1d26ea6768/create. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.io' is therefore not allowed access. The response had HTTP status code 504.
```

**Comment by ibuziuk** [comment]
Unidling UX is going to be significantly improved once https://github.com/fabric8-ui/fabric8-ui/issues/1825 is resolved and all idling related issues should be fixed with new UX

**Comment by joshuawilson** [comment]
This should be fixed in Prod now. @ldimaggi @ibuziuk please verify.

**Comment by l0rd** [comment]
Now, when Che is idle, and I open the codebase UI, I have a new kind of error:

![image](https://user-images.githubusercontent.com/606959/30153770-f9115e80-93b7-11e7-9b32-cd9f3d2574bd.png)

And I cannot see any evidence of che-starter trying to un-idle my Che (no events in the namespace).

**Comment by ldimaggi** [comment]
The original issue is still present.

Steps to recreate:
* Scale Che down to zero in the OpenShift Online console
* Attempt to create a codebase - observe the 504 errors written to the Chrome browser log:
![screenshot from 2017-09-07 08-17-51](https://user-images.githubusercontent.com/642621/30163034-56cad6b8-93a5-11e7-916e-f151e97f91bc.png)

* Eventually, Che un-idles and the workspace is opened - but there is no feedback to the user in the OSIO UI other than the spinning create icon - can we provide the user with more details while Che is un-idling? Thx!

**Comment by joshuawilson** [comment]
@dlabrecq can you please look at this.
@ldimaggi it looks like you might need a hard refresh.

**Comment by dlabrecq** [comment]
I suspect you'll need to reset your account to get the latest APIs. 

If you have the latest, the controls to create/open workspaces should be hidden while Che is starting. You should also see a "Your workspaces are loading" message.

**Comment by ibuziuk** [comment]
for me new approach with loading workspaces against idled che server works just fine. BTW, is https://github.com/fabric8-ui/fabric8-ui/issues/1825 done or smth. else is planed to implement as part of Async unidling

**Comment by dlabrecq** [comment]
#1825 is done.

**Comment by ibuziuk** [comment]
@ldimaggi the issue is supposed to be fixed. Could you please verify & close ?

**Comment by ldimaggi** [comment]
The error is no longer being seen - closing.
