### ISSUE TITLE
Work Items caching not working correctly

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#778]
New as of Sept 7th, previous work items are cached, despite a restarting of the Incognito window, despite the reseting of the environment
https://screencast.com/t/Eqd8qvLobTy
From the Board view, click on the WI to "assign to myself" but it opens a previously created WI in another browser session.

**Comment by joshuawilson** [comment]
@michaelkleinhenz any ideas?
cc @kbsingh @aslakknutsen

**Comment by michaelkleinhenz** [comment]
@burrsutter to track the problem down, please try to disable your browser cache (Dev Tools -> Network -> Disable Cache on the top of the dev window) and see if the problem goes away.

**Comment by michaelkleinhenz** [comment]
I think this is outdated now. There were no other reports on this since a while.

**Comment by Preeticp** [comment]
I saw this issue again today. I reset my environment, however I could still see work items from my previous Space in the Dashboard (Analyze tab). A refresh of the screen however fixes the issue and the stale work items are cleared.

**Comment by michaelkleinhenz** [comment]
@Preeticp How did you reset your environment? Because if you still stay inside the OSIO ui application, this could very well be caused by other issues than caching.

**Comment by joshuawilson** [comment]
@Preeticp how is this issue different then #1918? 
@michaelkleinhenz if you think it is something other then caching, can you have someone fix them. Meanwhile, it looks like we still have this issue.

**Comment by Preeticp** [comment]
@michaelkleinhenz, I navigated to Profile>Update Profile>Reset Environment. I was within the OSIO UI. I am not sure what the reason for the behavior is, but this is what I observed.

@joshuawilson this is different from #1918, Aslak gave a reason for the behavior in #1918, on hindsight, that was obvious and I have closed that one.
In this issue, you are able to see work items from a space which was deleted by the Reset environment.

**Comment by qodfathr** [comment]
Based upon the description, I wonder if this is a Planner bug or a Platform bug. The display of the work items on the account dashboard which is fixed via a refresh sounds like a Platform bug to me. We seem to have a few issues related to the various dashboards being able to react to changes made immediately before their display (e.g. after creating a new Space and running the App Wizard, the redirect to the Space dashboard shows "0 codebases" but a refresh fixes it.)

**Comment by joshuawilson** [comment]
That was my thought too. However, if @michaelkleinhenz thinks it is something else I don't want to hinder him from fixing it.

**Comment by michaelkleinhenz** [comment]
@joshuawilson @qodfathr Whatever caused this exact behaviour, we still have an issue with the caching. We're currently fundamentally changing how state data is managed in Planner by integrating ngrx/store in all components. This change will make analyzing the caching issue(s) much easier. We will likely finish this move in the next 2 sprints. So I would then look at this again.

**Comment by nimishamukherjee** [comment]
ngrx is in prod now. If anyone faces caching issues please reopen this issue.
