### ISSUE TITLE
SpringBoot Quick Start projects fail in Che

### ISSUE THREAD

**Issue by bmicklea** [openshiftio/openshift.io#798]
Neither of the Spring Boot quick start projects can be properly started in Che on OSIO.

### To Reproduce 
- Create space and use either of the Spring Boot quick starts.
- Space should appear correctly and builds kick off correctly.
- Go to Codebases section and create a Che workspace.
- Che IDE opens but workspace doesn't start. Error shown is`Workspace not running...` in the upper notification center, no other details

<img width="895" alt="screen shot 2017-09-12 at 11 28 57 am" src="https://user-images.githubusercontent.com/7644938/30334456-ab80cbd4-97ad-11e7-96c2-5b4ab7394b60.png">

- When running the workspace from the Workspace tab in the Che dashboard on OSIO you get this additional error:

<img width="531" alt="screen shot 2017-09-12 at 11 30 06 am" src="https://user-images.githubusercontent.com/7644938/30334543-e62030d6-97ad-11e7-8bd4-a3799a48f970.png">

### Environment
OSIO with Chrome (incognito) on OSX
Che 2.0.17
Jenkins 4.0.12

Confirmed by @DarrenRatcliffe

**Comment by bmicklea** [comment]
@l0rd and @gorkem - not sure if you're aware of this already but it's a problem since it seems to affect all spring boot project quick starts.

**Comment by l0rd** [comment]
@bmicklea no I was not. Let me try to reproduce it.

**Comment by l0rd** [comment]
I've reproduce it. And I confirm that vert.x quickstart work on Che so the problem is related to springboot stack only.

**Comment by bmicklea** [comment]
Thanks @l0rd.

**Comment by l0rd** [comment]
So it looks like using image `rhche/spring-boot` instead of `registry.devshift.net/che/spring-boot` as source of the stack solve the issue. These images should be identical.

**Comment by bmicklea** [comment]
So that's a change to the Che dockerfile?

**Comment by l0rd** [comment]
No the Dockerfiles are identical. But instead of using the Docker Hub for Docker images we have switched to registry.devshift.net late last week. I confirm that images are identical (same hash). There may be something in their name that osio don't like...continuing investigating

**Comment by ibuziuk** [comment]
```
2017-09-12 17:45:12,274[aceSharedPool-0]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 840]  - Created ImageStream registry.devshift.net_che_spring-boot.
--
  | 2017-09-12 17:45:14,443[aceSharedPool-0]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1437] - Created ImageStreamTag registry.devshift.net_che_spring-boot:che-ws-c067dx0sc9z4kbu79 in namespace ibuziuk-che
  | 2017-09-12 17:45:14,522[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - ImageStreamTag che-ws-c067dx0sc9z4kbu79ku1799htx0p3wyl not found!
  | org.eclipse.che.api.core.ServerException: ImageStreamTag che-ws-c067dx0sc9z4kbu79ku1799htx0p3wyl not found!
```

@l0rd looks like the problem is coupled with the fact that kubernetes names / labels max max lenght is 63 chars[1].  During IS creation the last part of the tag is trimmed:

> registry.devshift.net_che_spring-boot:che-ws-c067dx0sc9z4kbu79

But workspace manager tries to find IS tag by non-trimmed name `che-ws-c067dx0sc9z4kbu79ku1799htx0p3wyl` and fails. Basically, switching to a new registry has sufficiently increase IS naming prefix and we started to hit kubernetes names' length limmit

[1] https://github.com/kubernetes/kubernetes/issues/12463#issuecomment-129512910

**Comment by ibuziuk** [comment]
Have not tested but looks like decreasing length check to 25 should do the trick [1]

[1] https://github.com/eclipse/che/blob/master/plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftConnector.java#L1108

**Comment by ldimaggi** [comment]
Screenshot of the error:

![screenshot 40](https://user-images.githubusercontent.com/642621/30343012-d3a56a2c-97c9-11e7-97e1-3994de553d74.png)

**Comment by ibuziuk** [comment]
Duplicate - https://github.com/openshiftio/openshift.io/issues/798
Closing

**Comment by l0rd** [comment]
Thanks @ibuziuk for the analysis. @bmicklea we will fix that tomorrow.

**Comment by ibuziuk** [comment]
@l0rd tested on minishift - seems to work just fine.
This fix should work for all pre-defined rhche stacks - https://github.com/eclipse/che/pull/6245

**Comment by bmicklea** [comment]
Great news - thanks!

**Comment by l0rd** [comment]
@ibuziuk great job! Now we need to decide if:

- we ask Roman to do an hot fix release of eclipse/che that contains your fix
- we provide a temporary workaround (e.g. use `rhche/spring-boot` in [osio stacks.json](https://github.com/redhat-developer/rh-che/blob/master/builds/fabric8-che/assembly/fabric8-stacks/src/main/resources/stacks.json#L118)). 

I would rather go with this second option. It's easier and we will be able to fix the problem in prod in a less than an hour. @ibuziuk what do you think?

**Comment by ibuziuk** [comment]
@l0rd +1 for the second option, but we would also need to use rhche for all the other stacks (vertx seems to be the only one which is not affected)

**Comment by l0rd** [comment]
@ibuziuk https://github.com/redhat-developer/rh-che/pull/333

**Comment by l0rd** [comment]
Reopening it. PR is merged but we need to wait the build before it's available on OSIO.

**Comment by l0rd** [comment]
@bmicklea I've just verified that this is fixed on OSIO. Let me know if we can close it.

**Comment by ldimaggi** [comment]
Looks OK - Brad, is this working for you?

![screenshot 51](https://user-images.githubusercontent.com/642621/30386870-f06f15d6-9878-11e7-988d-c5cac8350731.png)

**Comment by bmicklea** [comment]
Strangely it's still not working for me on 2.0.18 - is that what you had @ldimaggi?

**Comment by ldimaggi** [comment]
Yes - 2.0.18 - just tried again and it was able to open the workspace.

**Comment by bmicklea** [comment]
It's working now, closing.

**Comment by ldimaggi** [comment]
Automated test to verify that each quickstart can open its Che workspace:
https://ci.centos.org/view/Devtools/job/devtools-test-end-to-end-openshift.io-chequickstartTest/

**Comment by l0rd** [comment]
@ldimaggi that is great!
I have a couple of questions:
- I really think that this test should be run before deploying any a new version of Che. Does it makes sense to add it as a final step of our rh-che build, just before promoting the build to prod?
- Is the source code and instruction to run this somewhere? It would be nice if we could run it locally to test our commits before pushing to github.

**Comment by ldimaggi** [comment]
Hey Brad:
* The tests are here: and can be run locally - https://github.com/fabric8io/fabric8-test/tree/master/ee_tests
* James S. is already running related tests in his build process - anyone else can do this too.
